config = {'train_data_path':['/root/autodl-tmp/LUNA16/subset_data/subset0/','/root/autodl-tmp/LUNA16/subset_data/subset1/','/root/autodl-tmp/LUNA16/subset_data/subset2/','/root/autodl-tmp/LUNA16/subset_data/subset3/','/root/autodl-tmp/LUNA16/subset_data/subset4/','/root/autodl-tmp/LUNA16/subset_data/subset5/','/root/autodl-tmp/LUNA16/subset_data/subset6/','/root/autodl-tmp/LUNA16/subset_data/subset7/','/root/autodl-tmp/LUNA16/subset_data/subset8/'],
          'val_data_path':['/root/autodl-tmp/LUNA16/subset_data/subset9/'], 
          'test_data_path':['/root/autodl-tmp/LUNA16/subset_data/subset9/'], 
          
          'train_preprocess_result_path':'/root/autodl-tmp/LUNA16/pre_process/', # contains numpy for the data and label, which is generated by prepare.py
          'val_preprocess_result_path':'/root/autodl-tmp/LUNA16/pre_process/',  # make sure copy all the numpy into one folder after prepare.py
          'test_preprocess_result_path':'/root/autodl-tmp/LUNA16/pre_process/',
          
          'train_annos_path':'/root/autodl-tmp/LUNA16/CSVFILES/annotations.csv',
          'val_annos_path':'/root/autodl-tmp/LUNA16/CSVFILES/annotations.csv',
          'test_annos_path':'/root/autodl-tmp/LUNA16/CSVFILES/annotations.csv',

          'black_list':[],
          
          'preprocessing_backend':'python',

          'luna_segment':'/root/autodl-tmp/LUNA16/seg-lungs-LUNA16/', # download from https://luna16.grand-challenge.org/data/
          'preprocess_result_path':'/root/autodl-tmp/LUNA16/pre_process/',
          'luna_data':'/root/autodl-tmp/LUNA16/subset_data/',
          'luna_label':'/root/autodl-tmp/LUNA16/CSVFILES/annotations.csv'
         } 
